### ISSUE TITLE
Missing lodash after npm install

### ISSUE THREAD

**Issue by hannupekka** [garbles/why-did-you-update#1]
Should lodash be moved to an actual dependency instead of development one?

**Comment by azz0r** [comment]
Same issue here, can't run this as I get the following errors:

    ERROR in ./~/why-did-you-update/lib/index.js
    Module not found: Error: Cannot resolve module 'lodash/isEqual' in /node_modules/why-did-you-update/lib
     @ ./~/why-did-you-update/lib/index.js 12:21-46

    ERROR in ./~/why-did-you-update/lib/index.js
    Module not found: Error: Cannot resolve module 'lodash/isFunction' in /node_modules/why-did-you-update/lib
     @ ./~/why-did-you-update/lib/index.js 16:24-52

    ERROR in ./~/why-did-you-update/lib/index.js
    Module not found: Error: Cannot resolve module 'lodash/isObject' in /node_modules/why-did-you-update/lib
     @ ./~/why-did-you-update/lib/index.js 20:22-48

    ERROR in ./~/why-did-you-update/lib/index.js
    Module not found: Error: Cannot resolve module 'lodash/keys' in /node_modules/why-did-you-update/lib
     @ ./~/why-did-you-update/lib/index.js 24:18-40

    ERROR in ./~/why-did-you-update/lib/index.js
    Module not found: Error: Cannot resolve module 'lodash/union' in /node_modules/why-did-you-update/lib
     @ ./~/why-did-you-update/lib/index.js 28:19-42

**Comment by export-mike** [comment]
referencing PR: https://github.com/garbles/why-did-you-update/pull/2

**Comment by garbles** [comment]
Fixed with https://github.com/garbles/why-did-you-update/pull/2!
