### ISSUE TITLE
Customizable console.warn vs console.error

### ISSUE THREAD

**Issue by scottluptowski** [garbles/why-did-you-update#11]
Great plugin.

I would love an option to specify if "Value did not change" messages should go through `console.error` or `console.warn`. In React Native, a `console.error` call triggers the red error screen and kills the app.

I'm happy to implement this myself and send over a PR if you have an API in mind for user-configured settings.

Thanks

**Comment by garbles** [comment]
> I would love an option to specify if "Value did not change" messages should go through console.error or console.warn. In React Native, a console.error call triggers the red error screen and kills the app.

🙊 I had no idea! Definitely into making this change.

**Comment by magus** [comment]
I like the idea of just using warnings everywhere instead. Seems overkill to have a flag to change error to warning in that one case.

**Comment by scottluptowski** [comment]
Yeah, that would make this a bit easier! From a React Native perspective there's never any re-rendering that is so important that I would want to kill the app during my development workflow, so a warning makes way more sense for that use case

**Comment by jokeyrhyme** [comment]
`console.error()` is useful when you want a stack trace, but it seems like this hook fairly accurately identifies the exact properties anyhow.

**Comment by garbles** [comment]
https://github.com/garbles/why-did-you-update/commit/8b2b7994c4a1e0b4154aba50111f2bf0f0df6385
