### ISSUE TITLE
Opt-in rather than ignore

### ISSUE THREAD

**Issue by artisologic** [garbles/why-did-you-update#12]
Really neat idea, I like it!

However I feel like it's not necessarily ideal in real life to have it turned on for all components.
The `ignore` option is a nice one, but I'd rather have an `include` option or something similar that does the opposite: Opt-in for specific components.

Typically that would help if you're concentrating on optimising a given component rather than being polluted by other components.

What do you think?

**Comment by garbles** [comment]
I think that's a great idea! 🎉  I'll probably do some work on this tonight if you don't already have something lined up.

**Comment by garbles** [comment]
https://github.com/garbles/why-did-you-update/commit/ebe363701797cac4b8d0c63ff1d1ee4ff50aebd3
