### ISSUE TITLE
Should string comparison be different from regex?

### ISSUE THREAD

**Issue by janhoogeveen** [garbles/why-did-you-update#15]
Right now the package is normalising strings into regex values so it can use the same .test() method in shouldInlude(). I think it might give false positives because it's not an equality check anymore but it checks if the string is found in a component names. That means a string exclusion called 'Bar' will also match a component named 'FooBar'.

See also https://github.com/garbles/why-did-you-update/pull/14 for the reason why I'm opening this issue.

**Comment by garbles** [comment]
I agree with you; however, it would still like to the options to be normalized. So instead of

```js
new Regexp(include)
```

we could try

```js
new Regexp(`^${include}$`)
```

to get an exact match?

**Comment by garbles** [comment]
https://github.com/garbles/why-did-you-update/commit/8da002a787a5e0e020c617f5005c3e2e6a898873
