### ISSUE TITLE
support React Native

### ISSUE THREAD

**Issue by gre** [garbles/why-did-you-update#22]
this is currently not working for me.
I'm getting an infinite stream of these logs and my app never boot:
<img width="402" alt="screen shot 2016-05-23 at 15 18 19" src="https://cloud.githubusercontent.com/assets/211411/15472102/ba448538-20f9-11e6-9505-726c0df0b12e.png">

**Comment by gre** [comment]
ok. actually that was a funky bug, but as React Native also renders the console.warn on the interface, there is an infinite loop going on with the library !

this can be fixed by doing: `whyDidYouUpdate(React, { exclude: /^YellowBox/ });`

**Comment by pokorson** [comment]
@garbles I've also came to this issue, maybe it would be good to add few 'common excludes' to documentaion?? Mind if I create a PR?
