### ISSUE TITLE
Looks like a cool patch. Where is the best place for the code?

### ISSUE THREAD

**Issue by manavsehgal** [garbles/why-did-you-update#3]
Where do you place the code within the app? Any suggestions if one is using Webpack?

**Comment by export-mike** [comment]
@manavsehgal put this in your index.js the main entry point to your app, first require to 'react'

**Comment by garbles** [comment]
Thanks @export-mike. We good here @manavsehgal?

**Comment by manavsehgal** [comment]
Sure thanks... I will give it a go!
