### ISSUE TITLE
Gives warning when items are appended to list, causing rerender.

### ISSUE THREAD

**Issue by happylinks** [garbles/why-did-you-update#30]
Hi, I'm wondering if this works when you append new items to a list.

I have a CollectionView:
```
const RowList = ({ rows }) => {
  return (
    <div>
      {rows.map(row => (
        <Row
          key={row.id}
          id={row.id}
          name={row.name}
        />
      ))}
    </div>
  );
};
```
Whenever I add items to the "rows" object, I want to render these rows.
By adding key={row.id}, React makes sure that components that are already rendered are not rerendered.
But unfortunately, why-did-you-update tells me that a part of the list is still the same, so I have to avoid the rerender:
```
RowPage.props.rows.0
deepDiff.js:38 Value did not change. Avoidable re-render!
RowPage.props.rows.1
deepDiff.js:38 Value did not change. Avoidable re-render!
```
etc.
Note that it gives this error on the component that contains the RowList, not on the RowList itself.

I'm wondering if the warning is correct and I should make changes to the data structure, or if why-did-you-update is giving me a false positive.

**Comment by caesarsol** [comment]
I think this package is meant to be used with Redux, or at least the same pattern Redux uses, which is based on immutable data structures.

You could avoid mutating the array but create a new one (by using `Array.prototype.concat` for example)

**Comment by happylinks** [comment]
That makes sense, thanks for the explanation.
