### ISSUE TITLE
react 0.14 devDeps with react 15.x.x?

### ISSUE THREAD

**Issue by export-mike** [garbles/why-did-you-update#4]
I'm not sure but could this cause issues for react@15 users?

https://github.com/garbles/why-did-you-update/blob/master/package.json#L25

**Comment by export-mike** [comment]
this could force some peoples apps to be downgraded to 0.14 react & react-dom

**Comment by export-mike** [comment]
I think what we need todo is change the dependencies on react-dom and react to both be peer dependencies.

**Comment by export-mike** [comment]
demo can have react 0.14 stuff I'll submit a PR

**Comment by garbles** [comment]
It won't cause an issue for react@15

**Comment by export-mike** [comment]
Interesting how can you be sure?

**Comment by garbles** [comment]
> I think what we need todo is change the dependencies on react-dom and react to both be peer dependencies.

The function doesn't have any direct dependency on React because it's never directly required. It only accepts a React-like object as an argument, i.e. this will also work with clones such as [Preact](https://github.com/developit/preact).

**Comment by export-mike** [comment]
You're also relying on getDisplayName to work. 

Yeah I'm in complete agreement with you on this, you've convinced me. 

I guess at this point you can say why-did-you-update bruh?
