### ISSUE TITLE
Crash when "Debug JS Remotely" is disabled

### ISSUE THREAD

**Issue by tomas-paronai** [garbles/why-did-you-update#49]
I always get this crash both o android and ios when I run the application in debug mode but I have not enabled "Debug JS Remotely". When I enable and refresh, than it works.
<img width="376" alt="screen shot 2017-08-07 at 10 15 16 am" src="https://user-images.githubusercontent.com/15670545/29021527-1886ea38-7b66-11e7-8422-c7a633b0b3b7.png">

**Comment by peteroid** [comment]
Since this has been in the fork(https://github.com/maicki/why-did-you-update), you can switch to the fork instead.

```
yarn add https://github.com/maicki/why-did-you-update.git
```

**Comment by parohy** [comment]
I am closing this issue, as this is not occurred anymore. 

@peteroid How is this relevant ?
